import React from "react"; import {PodState,Marker,WaveformData} from "./types"; import {Knob} from "./Knob"; import {HorizontalSlider} from "./Slider"; import {WaveformDisplay} from "./WaveformDisplay"; import {HardwareButton,PanelDivider,TechnicalLabel} from "./primitives"; import {SpeedControl} from "./SpeedControl"; import {flodeTokens} from "./tokens";
export function PodA({state,onChange,waveform,gridMarkers=[],sliceMarkers=[],transientMarkers=[],format}:{state:PodState;onChange:(s:PodState)=>void;waveform:WaveformData|null;gridMarkers?:Marker[];sliceMarkers?:Marker[];transientMarkers?:Marker[];format:{volume:(n:number)=>string;pan:(n:number)=>string;eq:(n:number)=>string;percent:(n:number)=>string;speed:(n:number)=>string}}){
 const set=<K extends keyof PodState>(k:K,v:PodState[K])=>onChange({...state,[k]:v}); const modes:PodState["genMode"][]=["PURE","JUNG","WEIGHTED","WALK","MEMORY","CHAOS"];
 return <section style={{maxWidth:1348,margin:"auto",padding:24,background:flodeTokens.color.chassis,border:`1px solid ${flodeTokens.color.panelBorder}`,fontFamily:flodeTokens.type.technical,color:flodeTokens.color.text}}>
 <header style={{display:"flex",alignItems:"center",justifyContent:"space-between"}}><div style={{display:"flex",alignItems:"baseline",gap:18}}><strong style={{fontSize:64,lineHeight:1,color:flodeTokens.color.primary}}>{state.id}</strong><span style={{fontFamily:flodeTokens.type.numeric,fontWeight:700}}>{state.sampleName??"NO SAMPLE"}</span></div><div style={{display:"flex",gap:8}}><HardwareButton>LOAD</HardwareButton><HardwareButton state={state.isMuted?"active":"idle"} onPress={()=>set("isMuted",!state.isMuted)}>MUTE</HardwareButton><HardwareButton state={state.isSolo?"active":"idle"} onPress={()=>set("isSolo",!state.isSolo)}>SOLO</HardwareButton></div></header><PanelDivider/>
 <div style={{display:"grid",gridTemplateColumns:`${flodeTokens.geometry.primaryRailRatio}fr ${flodeTokens.geometry.workSurfaceRatio}fr`,gap:24,paddingTop:18}}><aside style={{display:"grid",alignContent:"start",justifyItems:"center",gap:34,borderRight:`1px solid ${flodeTokens.color.divider}`}}><Knob label="VOLUME" valueNorm={state.volumeNorm} onChange={v=>set("volumeNorm",v)} valueText={format.volume(state.volumeNorm)} scale={[{label:"−∞",norm:0},{label:"+6",norm:1}]}/><Knob label="PAN" valueNorm={state.panNorm} onChange={v=>set("panNorm",v)} valueText={format.pan(state.panNorm)} scale={[{label:"L",norm:0},{label:"C",norm:.5},{label:"R",norm:1}]}/></aside>
 <main style={{display:"grid",gap:18}}><WaveformDisplay data={waveform} durationSeconds={state.durationSeconds} region={state.loopRegion} onRegionChange={v=>set("loopRegion",v)} playbackPosNorm={state.playbackPosNorm} gridMarkers={gridMarkers} sliceMarkers={sliceMarkers} transientMarkers={transientMarkers}/>
 <div style={{display:"flex",alignItems:"center",gap:8}}><TechnicalLabel>GEN MODE</TechnicalLabel>{modes.map(m=><HardwareButton key={m} variant="segmented" state={state.genMode===m?"selected":"idle"} onPress={()=>set("genMode",m)}>{m}</HardwareButton>)}</div><PanelDivider/>
 <div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:28}}><div style={{display:"grid",gap:18}}><HorizontalSlider label="RANDOM / JUNG" valueNorm={state.randomJungNorm} onChange={v=>set("randomJungNorm",v)} valueText={format.percent(state.randomJungNorm)}/><HorizontalSlider label="JITTER" valueNorm={state.jitterNorm} onChange={v=>set("jitterNorm",v)} valueText={format.percent(state.jitterNorm)} accentRole="jitter"/></div><div style={{display:"flex",justifyContent:"space-around",borderLeft:`1px solid ${flodeTokens.color.divider}`}}><Knob label="LOW" variant="eq" accentRole="eqLow" valueNorm={state.eqLowNorm} onChange={v=>set("eqLowNorm",v)} valueText={format.eq(state.eqLowNorm)}/><Knob label="MID" variant="eq" accentRole="eqMid" valueNorm={state.eqMidNorm} onChange={v=>set("eqMidNorm",v)} valueText={format.eq(state.eqMidNorm)}/><Knob label="HIGH" variant="eq" accentRole="eqHigh" valueNorm={state.eqHighNorm} onChange={v=>set("eqHighNorm",v)} valueText={format.eq(state.eqHighNorm)}/></div></div><PanelDivider/>
 <div style={{display:"flex",justifyContent:"space-between",alignItems:"center"}}><SpeedControl valueText={format.speed(state.speedMultiplier)}/><div style={{display:"flex",gap:12}}><HardwareButton variant="transport" state={state.isLoopActive?"active":"idle"} onPress={()=>set("isLoopActive",!state.isLoopActive)}>LOOP</HardwareButton><HardwareButton variant="transport" state={state.isSyncActive?"active":"idle"} onPress={()=>set("isSyncActive",!state.isSyncActive)}>SYNC</HardwareButton></div></div></main></div></section>
}
