import React,{useRef} from "react"; import {flodeTokens,AccentRole} from "./tokens"; import {TechnicalLabel,ValueDisplay} from "./primitives";
const clamp=(v:number)=>Math.max(0,Math.min(1,v));
export function HorizontalSlider({label,valueNorm,onChange,valueText,accentRole="primary"}:{label:string;valueNorm:number;onChange:(v:number)=>void;valueText:string;accentRole?:AccentRole}){
 const ref=useRef<HTMLDivElement>(null),col=flodeTokens.color[accentRole];
 const set=(x:number)=>{if(ref.current){const r=ref.current.getBoundingClientRect();onChange(clamp((x-r.left)/r.width))}};
 const down=(e:React.PointerEvent<HTMLDivElement>)=>{const el=e.currentTarget;el.setPointerCapture(e.pointerId);set(e.clientX);const mv=(p:PointerEvent)=>set(p.clientX);const clean=(p:PointerEvent)=>{if(el.hasPointerCapture(p.pointerId))el.releasePointerCapture(p.pointerId);el.removeEventListener("pointermove",mv);el.removeEventListener("pointerup",clean);el.removeEventListener("pointercancel",clean);el.removeEventListener("lostpointercapture",lost)};const lost=()=>{el.removeEventListener("pointermove",mv);el.removeEventListener("pointerup",clean);el.removeEventListener("pointercancel",clean)};el.addEventListener("pointermove",mv);el.addEventListener("pointerup",clean);el.addEventListener("pointercancel",clean);el.addEventListener("lostpointercapture",lost)};
 return <div style={{display:"grid",gap:5}}><TechnicalLabel>{label}</TechnicalLabel><div style={{display:"flex",gap:12,alignItems:"center"}}><div ref={ref} role="slider" aria-label={label} aria-valuemin={0} aria-valuemax={1} aria-valuenow={valueNorm} aria-valuetext={valueText} tabIndex={0} onPointerDown={down} style={{position:"relative",height:16,flex:1,background:flodeTokens.color.display,border:`1px solid ${flodeTokens.color.displayBorder}`,boxShadow:flodeTokens.depth.display,touchAction:"none"}}>
 <div style={{position:"absolute",inset:"0 auto 0 0",width:`${valueNorm*100}%`,background:col,opacity:.9}}/><div style={{position:"absolute",left:`calc(${valueNorm*100}% - 7px)`,top:-6,width:14,height:26,background:"#d4d7d8",border:"1px solid #111",boxShadow:flodeTokens.depth.raised}}><div style={{width:3,height:"100%",margin:"auto",background:col}}/></div></div><ValueDisplay value={valueText} accentRole={accentRole}/></div></div>
}
