import React,{useEffect,useRef} from "react"; import {flodeTokens} from "./tokens"; import {LoopRegion,Marker,WaveformData} from "./types"; import {ValueDisplay,TechnicalLabel} from "./primitives";
const clamp=(v:number)=>Math.max(0,Math.min(1,v)); const tc=(s:number|null)=>{if(s==null||!Number.isFinite(s)||s<0)return "--:--.---";const t=Math.round(s*1000),m=Math.floor(t/60000),sec=Math.floor((t%60000)/1000),ms=t%1000;return `${m}:${String(sec).padStart(2,"0")}.${String(ms).padStart(3,"0")}`};
function Wave({data,region}:{data:WaveformData|null;region:LoopRegion}){const ref=useRef<HTMLCanvasElement>(null);useEffect(()=>{const c=ref.current;if(!c)return;const r=c.getBoundingClientRect(),d=devicePixelRatio||1;c.width=Math.round(r.width*d);c.height=Math.round(r.height*d);const x=c.getContext("2d");if(!x)return;x.setTransform(d,0,0,d,0,0);x.fillStyle=flodeTokens.color.display;x.fillRect(0,0,r.width,r.height);if(!data?.peaks.length){x.strokeStyle="#333";x.beginPath();x.moveTo(0,r.height/2);x.lineTo(r.width,r.height/2);x.stroke();return}const bw=r.width/data.peaks.length;data.peaks.forEach((p,i)=>{const n=i/data.peaks.length,a=Math.min(1,Math.abs(p))*r.height*.42;x.fillStyle=n>=region.startNorm&&n<=region.endNorm?flodeTokens.color.primary:flodeTokens.color.primaryDim;x.fillRect(i*bw,r.height/2-a,Math.max(1,bw-1),a*2)})},[data,region]);return <canvas ref={ref} style={{width:"100%",height:"100%",display:"block"}}/>}
export function WaveformDisplay({data,durationSeconds,region,onRegionChange,playbackPosNorm,gridMarkers=[],sliceMarkers=[],transientMarkers=[]}:{data:WaveformData|null;durationSeconds:number|null;region:LoopRegion;onRegionChange:(r:LoopRegion)=>void;playbackPosNorm:number;gridMarkers?:Marker[];sliceMarkers?:Marker[];transientMarkers?:Marker[]}){
 const host=useRef<HTMLDivElement>(null),drag=(kind:"start"|"end",e:React.PointerEvent<HTMLDivElement>)=>{const el=e.currentTarget;el.setPointerCapture(e.pointerId);const move=(p:PointerEvent)=>{if(!host.current)return;const r=host.current.getBoundingClientRect(),n=clamp((p.clientX-r.left)/r.width),g=flodeTokens.geometry.minLoopGapNorm;onRegionChange(kind==="start"?{...region,startNorm:Math.min(n,region.endNorm-g)}:{...region,endNorm:Math.max(n,region.startNorm+g)})};const clean=(p:PointerEvent)=>{if(el.hasPointerCapture(p.pointerId))el.releasePointerCapture(p.pointerId);el.removeEventListener("pointermove",move);el.removeEventListener("pointerup",clean);el.removeEventListener("pointercancel",clean)};el.addEventListener("pointermove",move);el.addEventListener("pointerup",clean);el.addEventListener("pointercancel",clean)};
 const marker=(m:Marker,style:React.CSSProperties)=><div key={m.id} style={{position:"absolute",left:`${m.positionNorm*100}%`,top:0,bottom:0,...style}}/>;
 const handle=(k:"start"|"end",n:number)=><div onPointerDown={e=>drag(k,e)} style={{position:"absolute",left:`calc(${n*100}% - 10px)`,top:0,bottom:0,width:20,touchAction:"none",cursor:"ew-resize",zIndex:5}}><div style={{position:"absolute",left:9,top:0,bottom:0,width:2,background:flodeTokens.color.primary}}/><div style={{position:"absolute",left:4,top:0,width:0,height:0,borderLeft:"6px solid transparent",borderRight:"6px solid transparent",borderTop:`8px solid ${flodeTokens.color.primary}`}}/><div style={{position:"absolute",left:4,bottom:0,width:0,height:0,borderLeft:"6px solid transparent",borderRight:"6px solid transparent",borderBottom:`8px solid ${flodeTokens.color.primary}`}}/></div>;
 const dur=durationSeconds,start=dur==null?null:region.startNorm*dur,end=dur==null?null:region.endNorm*dur,len=start==null||end==null?null:end-start;
 return <div style={{background:flodeTokens.color.chassisDark,border:`1px solid ${flodeTokens.color.displayBorder}`,boxShadow:flodeTokens.depth.display,padding:8}}><div ref={host} style={{position:"relative",height:flodeTokens.geometry.waveformHeight,overflow:"hidden",background:flodeTokens.color.display}}>
 <Wave data={data} region={region}/>{gridMarkers.map(m=>marker(m,{borderLeft:"1px solid #262626"}))}{sliceMarkers.map(m=>marker(m,{borderLeft:`1px dashed ${flodeTokens.color.jitter}`}))}{transientMarkers.map(m=>marker(m,{borderLeft:`1px dotted ${flodeTokens.color.eqMid}`}))}<div style={{position:"absolute",left:`${region.startNorm*100}%`,width:`${(region.endNorm-region.startNorm)*100}%`,top:0,bottom:0,background:"rgba(255,107,0,.10)"}}/>{handle("start",region.startNorm)}{handle("end",region.endNorm)}<div style={{position:"absolute",left:`${clamp(playbackPosNorm)*100}%`,top:0,bottom:0,width:2,background:flodeTokens.color.playhead,zIndex:4}}/></div>
 <div style={{display:"grid",gridTemplateColumns:"1fr 1fr 1fr",gap:12,paddingTop:8}}>{[["LOOP START",tc(start)],["LENGTH",tc(len)],["LOOP END",tc(end)]].map(([l,v])=><div key={l} style={{display:"flex",alignItems:"center",gap:8}}><TechnicalLabel>{l}</TechnicalLabel><ValueDisplay value={v}/></div>)}</div></div>
}
